-- select a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, sum(b.PRICE*s.SALES) TOTAL_SALES
-- from BOOK b
-- join AUTHOR a on b.AUTHOR_ID = a.AUTHOR_ID
-- join BOOK_SALES s on b.BOOK_ID = s.BOOK_ID
-- where SALES_DATE >= '2022-01-01' and SALES_DATE < '2022-02-01'
-- group by a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
-- order by a.AUTHOR_ID, b.CATEGORY desc

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*BS.SALES) TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= TO_DATE('20220101', 'YYYYMMDD') 
    AND BS.SALES_DATE < TO_DATE('20220201', 'YYYYMMDD')
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC