select to_char(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
  and SALES_DATE <  TO_DATE('2022-04-01', 'YYYY-MM-DD')
  
union all

select to_char(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where SALES_DATE >= TO_DATE('2022-03-01', 'YYYY-MM-DD')
  and SALES_DATE <  TO_DATE('2022-04-01', 'YYYY-MM-DD')
  
order by SALES_DATE, PRODUCT_ID, USER_ID