WITH TMP AS (
    SELECT LEVEL-1 HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24)
    
SELECT HOUR, COUNT(DATETIME) COUNT
FROM TMP
LEFT JOIN ANIMAL_OUTS ON HOUR = TO_NUMBER(TO_CHAR(DATETIME,'HH24'))
GROUP BY HOUR
ORDER BY HOUR