SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U 
    ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
    HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES