select u.USER_ID, u.NICKNAME, sum(PRICE) TOTAL_SALES
from USED_GOODS_BOARD b
join USED_GOODS_USER u on b.WRITER_ID = u.USER_ID
where STATUS = 'DONE'
group by u.USER_ID, u.NICKNAME
having sum(PRICE) >= 700000
order by TOTAL_SALES