WITH TMP AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('20220801', 'YYYYMMDD')
        AND START_DATE < TO_DATE('20221101', 'YYYYMMDD')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)


SELECT EXTRACT(MONTH FROM START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM TMP)
    AND START_DATE >= TO_DATE('20220801', 'YYYYMMDD')
    AND START_DATE < TO_DATE('20221101', 'YYYYMMDD')
GROUP BY CAR_ID, EXTRACT(MONTH FROM START_DATE)
HAVING COUNT(*) <> 0
ORDER BY MONTH, CAR_ID DESC